# Generated by Django 4.1.3 on 2022-12-12 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_project_task_date_project_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task_date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
