# Generated by Django 4.1.3 on 2022-12-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_remove_user_confirmation_password_remove_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
