# Generated by Django 4.1.3 on 2022-12-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=30, unique=True)),
                ("fathers_name", models.CharField(max_length=40, unique=True)),
                ("mothers_name", models.CharField(max_length=30, unique=True)),
                ("age", models.IntegerField(max_length=20, null=True)),
                ("gender", models.CharField(max_length=10, null=True)),
                ("level", models.CharField(max_length=250, null=True)),
                ("department", models.CharField(max_length=25, null=True)),
                ("address", models.CharField(max_length=250, null=True)),
                ("email", models.EmailField(max_length=200, null=True)),
                ("pho_no", models.BigIntegerField(max_length=10, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("password", models.CharField(max_length=30, null=True)),
                ("confirmation_password", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
