# Generated by Django 4.1.3 on 2022-12-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_student_user_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="mothers_name",
            field=models.CharField(max_length=30),
        ),
    ]
