# Generated by Django 4.1.3 on 2022-12-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_alter_student_mothers_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="fathers_name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_name",
            field=models.CharField(max_length=30),
        ),
    ]
