# Generated by Django 4.1.3 on 2022-12-21 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_group_membership_person_delete_student_delete_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=30)),
                ("fathers_name", models.CharField(max_length=40)),
                ("mothers_name", models.CharField(max_length=30)),
                ("age", models.IntegerField(max_length=20, null=True)),
                ("gender", models.CharField(max_length=10, null=True)),
                ("level", models.CharField(max_length=250, null=True)),
                ("department", models.CharField(max_length=25, null=True)),
                ("address", models.CharField(max_length=250, null=True)),
                ("email", models.EmailField(max_length=200, null=True)),
                ("pho_no", models.BigIntegerField(max_length=10, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("password", models.CharField(max_length=30, null=True)),
                ("confirmation_password", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30, null=True)),
                ("password", models.CharField(max_length=50, null=True)),
                ("email", models.EmailField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="membership",
            name="group",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="person",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app1.user"
            ),
        ),
    ]
